### ISSUE TITLE
Binary data truncated when sending to AGWPE client

### ISSUE THREAD

**Issue by mfncooper** [wb2osz/direwolf#367]
In the server_send_monitored() function in server.c, binary data is being truncated and incompletely sent to the AGWPE client. The bug is caused by the use of strlcat() to copy the data on this line:

https://github.com/wb2osz/direwolf/blob/master/src/server.c#L925

Since NET/ROM data is binary, and frequently contains a null byte (e.g. as a sequence number), an AGWPE client does not receive the complete NET/ROM data, and cannot process it as such.

Also, I believe it is incorrect for Direwolf to be appending a '\r' to the end of the data here (on the next line, line 926). For binary data, it is certainly not appropriate, and for text data, it is very likely introducing inappropriate line ends where text is broken up across packets. The body of the I frame should contain only the binary data from the original AX.25 packet.

**Comment by wb2osz** [comment]
Thank you for your feedback.
After reviewing the interface specification, you are absolutely correct that binary data in the information part, of I and UI frames, should be handled properly.
This is fixed in the 'dev' branch.

The length issue requires some explanation.
The interface specification states that the client application should use the "Len=" value, from the header, to obtain the size of the information part of the frame. 
<I Sn Rn pid=nn Len=nn >
<UI pid=nn Len=nn >
The server might add additional bytes to the message, over the network, and the client should ignore them when interpreting the information part of the frame.  In the examples we see an extra \r and \0 being added.
