### ISSUE TITLE
libudev and UINT error in compiling on windows

### ISSUE THREAD

**Issue by Mas313** [wb2osz/direwolf#431]
I got error related to **libudev** and **UINT** when compiling on windows with cygwin and related packages installed

/usr/include/w32api/mmsystem.h:28:11: error: unknown type name ‘UINT’
   28 |   typedef UINT MMVERSION;
      |           ^~~~
compilation terminated due to -fmax-errors=1.
make[2]: *** [src/CMakeFiles/direwolf.dir/build.make:930: src/CMakeFiles/direwolf.dir/audio_win.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/cygdrive/e/Sotwares/direwolf-1.7-dev-A/src/cm108.c:135:10: fatal error: **libudev.h:** No such file or directory
  135 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/direwolf.dir/build.make:944: src/CMakeFiles/direwolf.dir/cm108.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1375: src/CMakeFiles/direwolf.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by wb2osz** [comment]
Compiling with Cygwin compiler is not supported.  I don't think that anyone else has ever asked for this.
I prefer the MinGW compiler because it generates native Windows code without the need for the Cygwin runtime,
If you would like to submit a code change to add compatibility, it would be welcome as long as it does not break the other platforms.

Use the MinGW compiler as described in the User Guide. 
https://github.com/wb2osz/direwolf/blob/dev/doc/User-Guide.pdf
This section: "4.6 Build Dire Wolf from source on Windows (optional)"

If the compiler is not in the normal location, environment variables must be set:

export CC=/usr/bin/x86_64-w64-mingw32-gcc
export CXX=/usr/bin/x86_64-w64-mingw32-g++
export AR=/usr/bin/x86_64-w64-mingw32-ar
export WINDRES=/usr/bin/x86_64-w64-mingw32-windres
