### ISSUE TITLE
How to compile source code for Ax.25 with FEC support Not other services required

### ISSUE THREAD

**Issue by Mas313** [wb2osz/direwolf#432]
Hello
How can i know the source file for AX.25 modem with FEC only and not any other like Gateways KISS TCP etc to get compile the modem only.  The Files are linked.

**Comment by wb2osz** [comment]
<p>

Here is list of the source file names and their functionality.   If you want a subset of the functionality, you can start removing parts you don't want and workaound all the resulting errors.  It would would be a significant amount of effort.  What is your real goal?  Why can't you use the complete application?

</p>



Name | Purpose
-- | --
aclients.c | Test   program for comparing reception from multiple TNCs, side by side.
ais.c | Processing   received AIS transmissions and converting to NMEA sentence representation.
aprs_tt.c | First half   of APRStt gateway.  Parse the tone   sequences and extract meaning from them.
atest.c | Test   fixture for using the demodulator with a file rather than live audio.
audio.c | Interface   to the “sound card” audio devices for Linux.
audio_portaudio.c | Interface   to the “sound card” audio devices for Mac OSX
audio_stats.c | Print   audio input stream statistics for troubleshooting.
audio_win.c | Interface   to the “sound card” audio devices for MS Windows.
ax25_link.c | AX.25 v2.2   Data Link State Machine for connected mode packet radio.
ax25_pad.c | Builds   packet objects from HDLC frames or text representation.  Extracts information, modifies them,   prepares for printing and transmission.
ax25_pad2.c | The   original ax25_pad.c was written with APRS in mind.  It handles UI frames and transparency for a   KISS TNC.  Here we add new functions   that can handle the more general cases of AX.25 frames.
beacon.c | Transmit   information periodically, either at a fixed rate or based on movement.
cdigipeater.c | Digipeater   for traditional connected mode packet.    APRS digipeater is in digipeater.c
config.c | Parse the   configuration file and put into a suitable form for later use.
decode_aprs.c | Decode   information part of an APRS frame.    Print in human readable format and point out problems.
dedupe.c | Avoid   transmitting duplicate packets which are too close together.
demod.c | Common   entry point for multiple types of demodulators.  This calls functions in demod_9600.c, demod_afsk.c   , or demod_psk.c, depending on the modem type selected.
demod_9600.c | Demodulator   for scrambled baseband encoding used by early hardware designs by G3RUH and   K9NG.
demod_afsk.c | Demodulator   for Audio Frequency Shift Keying (AFSK).
demod_psk.c | Demodulator   for Phase Shift Keying (PSK).
digipeater.c | Logic for   APRS digipeater.  UI frames only.  See cdigipeater.c for traditional connected   mode packet.
direwolf.c | Main   program.
dlq.c | Received   frame queue.
dsp.c | Generate   the filters used by the demodulators.
dtime_now.c | Returns   current time with more resolution than time() so we can measure short   intervals of elapsed time.
dtmf.c | Decoder   for DTMF, commonly known as "touch tones."
dwgps.c | Interface   for obtaining location from GPS.  This   is independent of whether we are using gpsd or reading NMEA sentences from a   serial port.
dwgpsd.c | Obtain GPS   information using gpsd.
dwgpsnmea.c | Read   directly from GPS over serial port and pars the NMEA sentences.
encode_aprs.c | Construct   APRS packets (e.g.  Position or Object   Report) from various parameters.
fc   s_calc.c | Calculate   the FCS for an AX.25 frame.
fx25_encode.c | FX.25
fx25_extract.c | FX.25
fx25_init.c | FX.25
fx25_rec.c | FX.25
fx25_send.c | FX.25
gen_packets.c | Test   program for generating AX.25 frames.     Given messages are converted to audio and written  to a .WAV type audio file.
gen_tone.c | Convert   bits to AFSK for writing to .WAV sound file or a sound device.
hdlc_rec.c | Extract   HDLC frames from a stream of bits.
hdlc_rec2.c | Extract   HDLC frame from a block of bits after someone else has done the work of   pulling it out from between  the   special "flag" sequences.
hdlc_send.c | Convert   HDLC frames to a stream of bits.
igate.c | IGate   client.  Establish connection with a   tier 2 IGate server and relay packets between RF and Internet.
Il2p_codec.c | IL2P
Il2p_header.c | IL2P
Il2p_init.c | IL2P
Il2p_payload.c | IL2P
Il2p_rec.c | IL2P
Il2p_scramble.c | IL2P
Il2p_send.c | IL2P
Il2p_test.c | IL2P
kiss.c | KISS TNC   via pseudo terminal.  Linux only.
kiss_frame.c | Common   code used by Serial port and network versions of KISS protocol.
kissnet.c | KISS TNC   over TCP.
Kissserial.c | KISS TNC   over serial port.
latlong.c | Various   functions for dealing with latitude and longitude.
ll2utm.c | Utility   for Latitude / Longitude to UTM conversion.
log.c | Save   received packets to a log file.
log2gpx.c | Separate   application for converting log file to GPX format.
mheard.c | Maintain a   list of all stations heard.
morse.c | Generate   audio for Morse Code.
multi_modem.c | Use   multiple modems in parallel to increase chances of decoding less than ideal   signals.   Pick the best one when there   are duplicates.
nmea.c | Send NMEA   waypoint sentences to GPS display or mapping application.
pfilter.c | Packet   filtering for digipeating or IGate.
ptt.c | Activate   the output control lines for push to talk (PTT) and other purposes.
rdq.c | Obsolete.  Should be removed.
recv.c | Process   audio input for receiving.
redecode.c | Obsolete.  Should be removed.
rrbb.c | Raw Received   Bit Buffer.  An array of bits used to   hold data out of the demodulator before feeding it into the HLDC decoding.
serial_port.c | Interface   to serial port, hiding operating system differences.
server.c | Provide   service to other applications via "AGW TCPIP Socket Interface".
symbols.c | Functions   related to the APRS symbols.
telemetry.c | Decode   APRS telemetry information.   Point out   where it violates the protocol spec and other applications might not   interpret it properly.
textcolor.c | All text output,   including color coding for different types of information.
tq.c | Transmit   queue - hold packets for transmission until the channel is clear.
tt_text.c | Translate   between text and touch tone representation.
tt_user.c | Second   half of APRStt gateway.  This maintains   a list of recently heard APRStt users and prepares "object" format   packets for transmission.
ttcalc.c | Simple   Touch Tone to Speech calculator.    Demonstration of how Dire Wolf can be used as a DTMF / Speech   interface for ham radio applications.
utm2ll.c | Utility   for UTM to Latitude / Longitude conversion.
walk96.c | Quick hack   to read GPS location and send very frequent position reports frames to a KISS   TNC.
waypoint.c | Send NMEA   waypoint sentences to GPS display or mapping application.
xid.c | Encode and   decode the info field of XID frames.
xmit.c | Transmit   queued up packets when channel is clear.



<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>
