### ISSUE TITLE
direwolf program cannot be opened

### ISSUE THREAD

**Issue by BH6ABO** [wb2osz/direwolf#514]
I want to use hamlib to control radio PTT. Because my radio cable does not support RTS/DTR

I installed hamlib correctly according to your user guide, and I also wrote the command under the DIREWOLF configuration file (PTT RIG 1043 COM9 9600).
After adding this line of command to the DIREWOLF configuration file I cannot open the program. I do not know why.
I'll take a video
[https://youtu.be/qPTpztqW3ng](url)

**Comment by dranch** [comment]
Github issues are for reporting bugs or requested new features.  For support, please join the direwolf@groups.io email list and re-post your question.  In that email, please state the operating system and OS version you're using.  Please also mention the version of direwolf and hamlib you're using.   As a side note, since you mentioned COM9, this means you're using Windows but the compiled version of Direwolf for Windows does not include Hamlib support.  One user has posted his binary that you can try if you don't want to compile it yourself.  Please read the following thread for more detail.

   https://groups.io/g/direwolf/topic/100098628#8418

Please close this github issue.

--David
