### ISSUE TITLE
9K6 GMSK Decodieren

### ISSUE THREAD

**Issue by Hackrfan** [wb2osz/direwolf#525]
Hello, I am new here.
Question. how do i have to configure dire wolf so that i can use 9k6 GMSK  
can decode. Telemetry Sonate-2 Satelit
Thanks for info
vy 73 Georg

**Comment by wb2osz** [comment]
According to   https://www.informatik.uni-wuerzburg.de/en/aerospaceinfo/mitarbeiter/kayal/forschungsprojekte/sonate-2/information-for-radio-amateurs/   the satellite uses normal AX.25 UI frames which direwolf can decode.

Telemetry downlink:
During passes over our ground stations in Germany the telemetry downlink will be activated.

Frequency: 437.025 MHz
Modulation: 9k6 G3RUH GMSK (F1D)
Protocol: AX.25

The protocol format used for encoding the telemetry frames can be found [>>here<<](https://www.informatik.uni-wuerzburg.de/fileadmin/1003-ifex/2024/SONATE-2_protocol_definition_for_radio_amateurs.xlsx)

The User Guide, and other documentation, explain how connect to a radio and configure to access an audio device.
You would need to add "MODEM 9600" to use 9600 bps G3RUH GMSK because the default is 1200 bps AFSK.

The information part of the frame is in a packed binary format so you would need something custom to make sense of it.

73,
John WB2OSZ
